language: r
cache: packages
r:
  - oldrel
  - release
  - devel
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings
branches:
  only:
  - main
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov()'
notifications:
  email:
    on_success: change
    on_failure: change
r_packages:
  - covr
bioc_required: true
env:
  global:
    - BIOC_USE_DEVEL="FALSE"  ## Use the current release version
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions
install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"
  - Rscript -e "devtools::install_github('cromanpa94/phruta')"
os:
  - linux
  - osx
warnings_are_errors: false
osx_image: xcode11.4
addons:
  apt:
    update: true

